
interface userHeaderContentProps {
    icon: string;
    title: string;
    stat: string;
    bgColor?: string;
}

interface userTableHeaderProps {
    titleHead: string;
    icon: string;
}

export type Payment = {
    id: string,
    organization: string,
    username: string,
    email: string,
    contact: string,
    date: string,
    status: "Pending" | "Inactive" | "Blacklisted" | "Active"

    fullName: string,
    UserTier: number,
    amount: number,
    accountNo: string,
    bankName: string,
    customerImage: string,
    maritalStatus: string,
    children: string,
    ResidenceType: string,
    bvn: string,
    gender: string,

    educationLevel: string,
    employmentStatus: string,
    employmentSector: string,
    employmentDuration: string,
    officeEmail: string,
    monthlyIncome: string,
    loanRepayment: string,

    twitter: string,
    facebook: string,
    instagram: string,

    guarantorFullName: string,
    guarantorContact: string,
    guarantorEmail: string,
    relationship: string,
}


export const data: Payment[] = [
    {
        id: "5kma53ae",
        organization: "Lendsqr",
        username: "Adedeji",
        email: "adedeji@lendsqr.com",
        contact: "08078903721",
        date: "May 15, 2020 10:00 AM",
        status: "Inactive",

        fullName: "Grace Effiong",
        UserTier: 1,
        amount: 200000.00,
        accountNo: "867495768",
        bankName: "Providus Bank",
        customerImage: "/images/customer.svg",
        maritalStatus: "Single",
        children: "None",
        ResidenceType: "Parent's Apartment",
        bvn: "95874652345",
        gender: "female",

        educationLevel: "B.sc",
        employmentStatus: "Employed",
        employmentSector: "FinTech",
        employmentDuration: "2",
        officeEmail: "grace@lendsqr.com",
        monthlyIncome: "200,000.00 - 400,000.00",
        loanRepayment: "40,000",

        twitter: "@grace_effiom",
        facebook: "Grace Effiom",
        instagram: "@grace_effiom",

        guarantorFullName: "Debby Ogana",
        guarantorContact: "0706078922",
        guarantorEmail: "debby@gmail.com",
        relationship: "Sister",

    },
    {
        id: "bhqecj4p",
        organization: "Irorun",
        username: "Adedeji",
        email: "adedeji@lendsqr.com",
        contact: "08078903721",
        date: "May 15, 2020 10:00 AM",
        status: "Pending",

        fullName: "Adedeji Effiong",
        UserTier: 1,
        amount: 200000.00,
        accountNo: "867495768",
        bankName: "Providus Bank",
        customerImage: "/images/customer.svg",
        maritalStatus: "Single",
        children: "None",
        ResidenceType: "Parent's Apartment",
        bvn: "95874652345",
        gender: "female",

        educationLevel: "B.sc",
        employmentStatus: "Employed",
        employmentSector: "FinTech",
        employmentDuration: "2",
        officeEmail: "grace@lendsqr.com",
        monthlyIncome: "200,000.00 - 400,000.00",
        loanRepayment: "40,000",

        twitter: "@grace_effiom",
        facebook: "Grace Effiom",
        instagram: "@grace_effiom",

        guarantorFullName: "Debby Ogana",
        guarantorContact: "0706078922",
        guarantorEmail: "debby@gmail.com",
        relationship: "Sister",
    },
    {
        id: "derv1ws0",
        organization: "Lendsqr",
        username: "Adedeji",
        email: "adedeji@lendsqr.com",
        contact: "08078903721",
        date: "May 15, 2020 10:00 AM",
        status: "Blacklisted",

        fullName: "Grace Effiong",
        UserTier: 1,
        amount: 200000.00,
        accountNo: "867495768",
        bankName: "Providus Bank",
        customerImage: "/images/customer.svg",
        maritalStatus: "Single",
        children: "None",
        ResidenceType: "Parent's Apartment",
        bvn: "95874652345",
        gender: "female",

        educationLevel: "B.sc",
        employmentStatus: "Employed",
        employmentSector: "FinTech",
        employmentDuration: "2",
        officeEmail: "grace@lendsqr.com",
        monthlyIncome: "200,000.00 - 400,000.00",
        loanRepayment: "40,000",

        twitter: "@grace_effiom",
        facebook: "Grace Effiom",
        instagram: "@grace_effiom",

        guarantorFullName: "Debby Ogana",
        guarantorContact: "0706078922",
        guarantorEmail: "debby@gmail.com",
        relationship: "Sister",
    },
    {
        id: "3u1reuv4",
        organization: "Lendsqr",
        username: "Adedeji",
        email: "adedeji@lendsqr.com",
        contact: "08078903721",
        date: "May 15, 2020 10:00 AM",
        status: "Active",

        fullName: "Grace Effiong",
        UserTier: 1,
        amount: 200000.00,
        accountNo: "867495768",
        bankName: "Providus Bank",
        customerImage: "/images/customer.svg",
        maritalStatus: "Single",
        children: "None",
        ResidenceType: "Parent's Apartment",
        bvn: "95874652345",
        gender: "female",

        educationLevel: "B.sc",
        employmentStatus: "Employed",
        employmentSector: "FinTech",
        employmentDuration: "2",
        officeEmail: "grace@lendsqr.com",
        monthlyIncome: "200,000.00 - 400,000.00",
        loanRepayment: "40,000",

        twitter: "@grace_effiom",
        facebook: "Grace Effiom",
        instagram: "@grace_effiom",

        guarantorFullName: "Debby Ogana",
        guarantorContact: "0706078922",
        guarantorEmail: "debby@gmail.com",
        relationship: "Sister",
    },
    {
        id: "m5gr84i9",
        organization: "Lendsqr",
        username: "Adedeji",
        email: "adedeji@lendsqr.com",
        contact: "08078903721",
        date: "May 15, 2020 10:00 AM",
        status: "Inactive",

        fullName: "Grace Effiong",
        UserTier: 1,
        amount: 200000.00,
        accountNo: "867495768",
        bankName: "Providus Bank",
        customerImage: "/images/customer.svg",
        maritalStatus: "Single",
        children: "None",
        ResidenceType: "Parent's Apartment",
        bvn: "95874652345",
        gender: "female",

        educationLevel: "B.sc",
        employmentStatus: "Employed",
        employmentSector: "FinTech",
        employmentDuration: "2",
        officeEmail: "grace@lendsqr.com",
        monthlyIncome: "200,000.00 - 400,000.00",
        loanRepayment: "40,000",

        twitter: "@grace_effiom",
        facebook: "Grace Effiom",
        instagram: "@grace_effiom",

        guarantorFullName: "Debby Ogana",
        guarantorContact: "0706078922",
        guarantorEmail: "debby@gmail.com",
        relationship: "Sister",
    },
    {
        id: "5kma53ae",
        organization: "Lendsqr",
        username: "Adedeji",
        email: "adedeji@lendsqr.com",
        contact: "08078903721",
        date: "May 15, 2020 10:00 AM",
        status: "Inactive",

        fullName: "Grace Effiong",
        UserTier: 1,
        amount: 200000.00,
        accountNo: "867495768",
        bankName: "Providus Bank",
        customerImage: "/images/customer.svg",
        maritalStatus: "Single",
        children: "None",
        ResidenceType: "Parent's Apartment",
        bvn: "95874652345",
        gender: "female",

        educationLevel: "B.sc",
        employmentStatus: "Employed",
        employmentSector: "FinTech",
        employmentDuration: "2",
        officeEmail: "grace@lendsqr.com",
        monthlyIncome: "200,000.00 - 400,000.00",
        loanRepayment: "40,000",

        twitter: "@grace_effiom",
        facebook: "Grace Effiom",
        instagram: "@grace_effiom",

        guarantorFullName: "Debby Ogana",
        guarantorContact: "0706078922",
        guarantorEmail: "debby@gmail.com",
        relationship: "Sister",
    },
    {
        id: "bhqecj4p",
        organization: "Lendsqr",
        username: "Adedeji",
        email: "adedeji@lendsqr.com",
        contact: "08078903721",
        date: "May 15, 2020 10:00 AM",
        status: "Pending",

        fullName: "Grace Effiong",
        UserTier: 1,
        amount: 200000.00,
        accountNo: "867495768",
        bankName: "Providus Bank",
        customerImage: "/images/customer.svg",
        maritalStatus: "Single",
        children: "None",
        ResidenceType: "Parent's Apartment",
        bvn: "95874652345",
        gender: "female",

        educationLevel: "B.sc",
        employmentStatus: "Employed",
        employmentSector: "FinTech",
        employmentDuration: "2",
        officeEmail: "grace@lendsqr.com",
        monthlyIncome: "200,000.00 - 400,000.00",
        loanRepayment: "40,000",

        twitter: "@grace_effiom",
        facebook: "Grace Effiom",
        instagram: "@grace_effiom",

        guarantorFullName: "Debby Ogana",
        guarantorContact: "0706078922",
        guarantorEmail: "debby@gmail.com",
        relationship: "Sister",
    },
    {
        id: "derv1ws0",
        organization: "Lendsqr",
        username: "Adedeji",
        email: "adedeji@lendsqr.com",
        contact: "08078903721",
        date: "May 15, 2020 10:00 AM",
        status: "Blacklisted",

        fullName: "Grace Effiong",
        UserTier: 1,
        amount: 200000.00,
        accountNo: "867495768",
        bankName: "Providus Bank",
        customerImage: "/images/customer.svg",
        maritalStatus: "Single",
        children: "None",
        ResidenceType: "Parent's Apartment",
        bvn: "95874652345",
        gender: "female",

        educationLevel: "B.sc",
        employmentStatus: "Employed",
        employmentSector: "FinTech",
        employmentDuration: "2",
        officeEmail: "grace@lendsqr.com",
        monthlyIncome: "200,000.00 - 400,000.00",
        loanRepayment: "40,000",

        twitter: "@grace_effiom",
        facebook: "Grace Effiom",
        instagram: "@grace_effiom",

        guarantorFullName: "Debby Ogana",
        guarantorContact: "0706078922",
        guarantorEmail: "debby@gmail.com",
        relationship: "Sister",
    },
    {
        id: "3u1reuv4",
        organization: "Lendsqr",
        username: "Adedeji",
        email: "adedeji@lendsqr.com",
        contact: "08078903721",
        date: "May 15, 2020 10:00 AM",
        status: "Active",

        fullName: "Grace Effiong",
        UserTier: 1,
        amount: 200000.00,
        accountNo: "867495768",
        bankName: "Providus Bank",
        customerImage: "/images/customer.svg",
        maritalStatus: "Single",
        children: "None",
        ResidenceType: "Parent's Apartment",
        bvn: "95874652345",
        gender: "female",

        educationLevel: "B.sc",
        employmentStatus: "Employed",
        employmentSector: "FinTech",
        employmentDuration: "2",
        officeEmail: "grace@lendsqr.com",
        monthlyIncome: "200,000.00 - 400,000.00",
        loanRepayment: "40,000",

        twitter: "@grace_effiom",
        facebook: "Grace Effiom",
        instagram: "@grace_effiom",

        guarantorFullName: "Debby Ogana",
        guarantorContact: "0706078922",
        guarantorEmail: "debby@gmail.com",
        relationship: "Sister",
    },
    {
        id: "m5gr84i9",
        organization: "Lendsqr",
        username: "Adedeji",
        email: "adedeji@lendsqr.com",
        contact: "08078903721",
        date: "May 15, 2020 10:00 AM",
        status: "Inactive",

        fullName: "Grace Effiong",
        UserTier: 1,
        amount: 200000.00,
        accountNo: "867495768",
        bankName: "Providus Bank",
        customerImage: "/images/customer.svg",
        maritalStatus: "Single",
        children: "None",
        ResidenceType: "Parent's Apartment",
        bvn: "95874652345",
        gender: "female",

        educationLevel: "B.sc",
        employmentStatus: "Employed",
        employmentSector: "FinTech",
        employmentDuration: "2",
        officeEmail: "grace@lendsqr.com",
        monthlyIncome: "200,000.00 - 400,000.00",
        loanRepayment: "40,000",

        twitter: "@grace_effiom",
        facebook: "Grace Effiom",
        instagram: "@grace_effiom",

        guarantorFullName: "Debby Ogana",
        guarantorContact: "0706078922",
        guarantorEmail: "debby@gmail.com",
        relationship: "Sister",
    },
]



export const userHeaderContent: userHeaderContentProps[] = [
    {
        icon: "/images/user1.png",
        title: "Users",
        stat: "2,453",
        bgColor: "#DF18FF",
    },
    {
        icon: "/images/user2.png",
        title: "Active Users",
        stat: "2,453",
        bgColor: "#5718FF",
    },
    {
        icon: "/images/user3.png",
        title: "Users with Loans",
        stat: "12,453",
        bgColor: "#F55F44",
    },
    {
        icon: "/images/user4.png",
        title: "Users with savings",
        stat: "102,453",
        bgColor: "#FF3366",
    },
]


export const userTableHeader: userTableHeaderProps[] = [
    {
        titleHead: "Organization",
        icon: "/images/filter.png",
    },
    {
        titleHead: "Username",
        icon: "/images/filter.png",
    },
    {
        titleHead: "Email",
        icon: "/images/filter.png",
    },
    {
        titleHead: "Phone Number",
        icon: "/images/filter.png",
    },
    {
        titleHead: "Date Joined",
        icon: "/images/filter.png",
    },
    {
        titleHead: "Status",

        fullName: "Grace Effiong",
        UserTier: 1,
        amount: 200000.00,
        accountNo: "867495768",
        bankName: "Providus Bank",
        customerImage: "/images/customer.svg",
        maritalStatus: "Single",
        children: "None",
        ResidenceType: "Parent's Apartment",
        bvn: "95874652345",
        gender: "female",

        educationLevel: "B.sc",
        employmentStatus: "Employed",
        employmentSector: "FinTech",
        employmentDuration: "2",
        officeEmail: "grace@lendsqr.com",
        monthlyIncome: "200,000.00 - 400,000.00",
        loanRepayment: "40,000",

        twitter: "@grace_effiom",
        facebook: "Grace Effiom",
        instagram: "@grace_effiom",

        guarantorFullName: "Debby Ogana",
        guarantorContact: "0706078922",
        guarantorEmail: "debby@gmail.com",
        relationship: "Sister",
        icon: "/images/filter.png",
    },
]



